To read from a database into a pandas dataframe, we use another library called SQLAlchemy. This is already available on datasciencehub.

First, let's open our CSV (`Calgary_Public_Library_Locations_and_Hours.csv`) in pandas. 

This CSV is provided courtesy of the City of Calgary, under the Open Government License, and can be found here: https://data.calgary.ca/Recreation-and-Culture/Calgary-Public-Library-Locations-and-Hours/m9y7-ui7j

First, let's review the data we will be using, and read it into a DataFrame.

In [11]:
import pandas as pd

cpl_locations = pd.read_csv("Calgary_Public_Library_Locations_and_Hours.csv")
cpl_locations.head()

,Library,Postal_Code,Square_Feet,Phone_Number,Monday_Open,Monday_Close,Tuesday_Open,Tuesday_Close,Wednesday_Open,Wednesday_Close,Thursday_Open,Thursday_Close,Friday_Open,Friday_Close,Saturday_Open,Saturday_Close,Sunday_Open,Sunday_Close,Address
0,W.R. Castell Central Library,T2G 2M2,177532,403-260-2600,9:00,20:00,9:00,20:00,9:00,20:00,9:00,20:00,9:00,17:00,10:00,17:00,12:00,17:00,"616 Macleod Tr SE\n(51.0470276, -114.0578995)"
1,Alexander Calhoun Library,T2T 3V8,9256,403-260-2600,10:00,21:00,10:00,21:00,10:00,21:00,10:00,21:00,10:00,18:00,10:00,17:00,12:00,17:00,"3223 14 St SW\n(51.0255318, -114.0947876)"
2,Bowness Library,T3B 0H3,7800,403-260-2600,13:00,20:00,10:00,20:00,10:00,20:00,10:00,17:00,10:00,17:00,10:00,17:00,12:00,17:00,"7930 Bowness Rd NW\n(51.0872841, -114.1830978)"
3,Fish Creek Library,T2J 6S1,47074,403-260-2600,9:00,21:00,9:00,21:00,9:00,21:00,9:00,21:00,9:00,18:00,9:00,17:00,12:00,17:00,"11161 Bonaventure Dr SE\n(50.9516296, -114.060..."
4,Forest Lawn Library,T2A 4M1,16977,403-260-2600,10:00,21:00,10:00,21:00,10:00,21:00,10:00,21:00,10:00,18:00,10:00,17:00,12:00,17:00,"4807 8 Av SE\n(51.045105, -113.9652023)"

In [12]:
import sqlalchemy as sq
sq.__version__

'1.4.40'

To create a connection, we create an _engine_ object

In [13]:
# fill in the details for your username and password below 

engine = sq.create_engine('mysql+mysqlconnector://zheyu_song:5QFH73NUI@datasciencedb.ucalgary.ca/zheyu_song')

In [14]:
cpl_locations.to_sql('library_locations', engine )

18

In [15]:
# What is the SQL equivalent of this method call?

library_df = pd.read_sql_table("library_locations", engine)
library_df.head()

,index,Library,Postal_Code,Square_Feet,Phone_Number,Monday_Open,Monday_Close,Tuesday_Open,Tuesday_Close,Wednesday_Open,Wednesday_Close,Thursday_Open,Thursday_Close,Friday_Open,Friday_Close,Saturday_Open,Saturday_Close,Sunday_Open,Sunday_Close,Address
0,0,W.R. Castell Central Library,T2G 2M2,177532,403-260-2600,9:00,20:00,9:00,20:00,9:00,20:00,9:00,20:00,9:00,17:00,10:00,17:00,12:00,17:00,"616 Macleod Tr SE\n(51.0470276, -114.0578995)"
1,1,Alexander Calhoun Library,T2T 3V8,9256,403-260-2600,10:00,21:00,10:00,21:00,10:00,21:00,10:00,21:00,10:00,18:00,10:00,17:00,12:00,17:00,"3223 14 St SW\n(51.0255318, -114.0947876)"
2,2,Bowness Library,T3B 0H3,7800,403-260-2600,13:00,20:00,10:00,20:00,10:00,20:00,10:00,17:00,10:00,17:00,10:00,17:00,12:00,17:00,"7930 Bowness Rd NW\n(51.0872841, -114.1830978)"
3,3,Fish Creek Library,T2J 6S1,47074,403-260-2600,9:00,21:00,9:00,21:00,9:00,21:00,9:00,21:00,9:00,18:00,9:00,17:00,12:00,17:00,"11161 Bonaventure Dr SE\n(50.9516296, -114.060..."
4,4,Forest Lawn Library,T2A 4M1,16977,403-260-2600,10:00,21:00,10:00,21:00,10:00,21:00,10:00,21:00,10:00,18:00,10:00,17:00,12:00,17:00,"4807 8 Av SE\n(51.045105, -113.9652023)"

In [16]:
# Now try a query

query_table = pd.read_sql_query('select postal_code from library_locations;', engine)
print (query_table)

   postal_code
0      T2G 2M2
1      T2T 3V8
2      T3B 0H3
3      T2J 6S1
4      T2A 4M1
5      T2C 2N5
6      T2N 1M5
7      T2R 0W5
8      T2L 0G6
9      T2Y 4H3
10     T3H 3P8
11     T2W 0J9
12     T2K 4Y5
13     T1Y 6E7
14     T3G 5T3
15     T3K 6E3
16     T3J 0C9
17     T3C 1P4

In [17]:
# Another query

query2_table = pd.read_sql_query('select * from library_locations where postal_code like "t2%";', engine)
query2_table.head()

,index,Library,Postal_Code,Square_Feet,Phone_Number,Monday_Open,Monday_Close,Tuesday_Open,Tuesday_Close,Wednesday_Open,Wednesday_Close,Thursday_Open,Thursday_Close,Friday_Open,Friday_Close,Saturday_Open,Saturday_Close,Sunday_Open,Sunday_Close,Address
0,0,W.R. Castell Central Library,T2G 2M2,177532,403-260-2600,9:00,20:00,9:00,20:00,9:00,20:00,9:00,20:00,9:00,17:00,10:00,17:00,12:00,17:00,"616 Macleod Tr SE\n(51.0470276, -114.0578995)"
1,1,Alexander Calhoun Library,T2T 3V8,9256,403-260-2600,10:00,21:00,10:00,21:00,10:00,21:00,10:00,21:00,10:00,18:00,10:00,17:00,12:00,17:00,"3223 14 St SW\n(51.0255318, -114.0947876)"
2,3,Fish Creek Library,T2J 6S1,47074,403-260-2600,9:00,21:00,9:00,21:00,9:00,21:00,9:00,21:00,9:00,18:00,9:00,17:00,12:00,17:00,"11161 Bonaventure Dr SE\n(50.9516296, -114.060..."
3,4,Forest Lawn Library,T2A 4M1,16977,403-260-2600,10:00,21:00,10:00,21:00,10:00,21:00,10:00,21:00,10:00,18:00,10:00,17:00,12:00,17:00,"4807 8 Av SE\n(51.045105, -113.9652023)"
4,5,Glenmore Square Library,T2C 2N5,6068,403-260-2600,10:00,21:00,10:00,21:00,13:00,21:00,10:00,21:00,10:00,17:00,10:00,17:00,12:00,17:00,"7740 18 St SE\n(50.9835968, -114.0141449)"

NameError: name 'a' is not defined